### ISSUE TITLE
Hibernate-redis and Amazon Elasticache

### ISSUE THREAD

**Issue by CeccoCQ** [debop/hibernate-redis#12]
Hi,

I'm working with hibernate-redis project.
I've a MySQL database with all entities marked with this annotations:

@Cacheable
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE, region="MyEntity")

and for each @OneToMany relationships, I've:
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE, region="MyEntity.MyEntity2")

In my hibernate-redis.properties I've set these fields:

redis.host=myamazonhost
redis.port=6379
redis.database=1
redis.expiryInSeconds=120
redis.expiryInSeconds.hibernate.common=0
redis.expiryInSeconds.hibernate.account=1200

and in my hibernate config:
```java
Map<String, String> props = new HashMap<String, String>(configuration.getDatabaseConfiguration().getProperties());
props.put(org.hibernate.cfg.Environment.USE_SECOND_LEVEL_CACHE, "true");
props.put(org.hibernate.cfg.Environment.USE_QUERY_CACHE, "true");
props.put(org.hibernate.cfg.Environment.GENERATE_STATISTICS, "true");               
props.put(org.hibernate.cfg.Environment.CACHE_REGION_FACTORY,SingletonRedisRegionFactory.class.getName());
props.put(org.hibernate.cfg.Environment.CACHE_REGION_PREFIX, "hibernate:");
props.put(org.hibernate.cfg.Environment.GENERATE_STATISTICS, "true");
props.put(org.hibernate.cfg.Environment.USE_STRUCTURED_CACHE, "true");
props.put(org.hibernate.cfg.Environment.TRANSACTION_STRATEGY, JdbcTransactionFactory.class.getName());
```
.....with no connection problems.

But, when I query the MyEntity table, in my redis-cli monitor I've:

"hset" "hibernate:.MyEntity" "com.myproject.MyEntity#14" "\xac\xed\x00.................... etc"

so I think that the entry was added to cache.
But when I execute the command KEYS * into redis shell, I've only:
1) "ElastiCacheMasterReplicationTimestamp"

Why? Where I wrong?

**Comment by debop** [comment]
hibernate-redis 2.0.0 using Redisson.
Redisson support Redis Cluster, Elasticache, Sentinel, Master-Slaves.
try 2.0.0
