### ISSUE TITLE
Concurrent access

### ISSUE THREAD

**Issue by nottix** [debop/hibernate-redis#25]
If two hibernate instance with hibernate-redis accesses concurrently at same resource, can occur a race condition?

1. B make a slow query.
1. A make a fast query and put a new element in cache, named test1 with value X;
2. B finish its slow query and modify test1 element changing its value to Y.

But the most updated value is X.

**Comment by bostanio** [comment]
There is now distributed Timestamper support added as part of this pull request: https://github.com/hibernate-redis/hibernate-redis/pull/2. I would hope that this fixes the problem you see but it would need to be tested.

Note that we are now maintaining an active fork an publishing releases from here: https://github.com/hibernate-redis/hibernate-redis

**Comment by nottix** [comment]
Thank you @bostanio

**Comment by debop** [comment]
@bostanio Thanks ^^
