### ISSUE TITLE
Allow JedisTool cacheProps to be set without going through the JedisTool

### ISSUE THREAD

**Issue by bostanio** [debop/hibernate-redis#32]
The indirection of the DataRegions calling static methods to get their expiration times requires all you to go through the JedisTool to create a JedisClient etc. This is awkward in many situations in particular for plugins such as the Grails wrapper that is currently bypassing that configuration altogether (and hence not getting configuration per cache region:

https://github.com/Alotor/grails-redis-hibernate-cache/blob/master/src/java/org/hibernate/cache/redis/GrailsRedisRegionFactory.java

It would be better if the RegionFactory stored all its properties and cacheProps in the parent class and then had the various DataRegions read their expiry key from that list of properties.

That would would allow consumers to create RegionFactories in more flexible ways in particular to supply the expiration properties in the original properties rather than being forced to use a external file and set Environment.CACHE_PROVIDER_CONFIG. (which is very much not the configuration style of Grails plugins etc. etc.)

**Comment by debop** [comment]
Sorry no response ㅠ.ㅠ
