### ISSUE TITLE
Release it on central

### ISSUE THREAD

**Issue by kreyssel** [debop/hibernate-redis#39]
Hi,

do you think you are able to release your project on maven central or bintray? Would be great! :)

It's a great project!

Thanks
Conny

**Comment by johnou** [comment]
@kreyssel I have forked this project with bostanio and it has been deployed to central maven. See https://github.com/hibernate-redis/hibernate-redis

**Comment by debop** [comment]
Thanks @johnou 
please join this project please.

**Comment by debop** [comment]
@kreyssel 
Release to jcenter (http://jcenter.bintray.com) 
please use jcenter

**Comment by johnou** [comment]
@debop when I get back from holiday I will take care of getting this library into Maven central.

**Comment by debop** [comment]
@johnou Thank you ^^

**Comment by johnou** [comment]
@debop unfortunately the gradle shadow plugin does not support sources jar out of the box see https://github.com/johnrengelman/shadow/issues/112 and https://github.com/johnrengelman/shadow/issues/41 , if I cannot get it working would you be against reverting back to Maven..?

**Comment by johnou** [comment]
The other option is to drop the shaded jar and ship individual artifacts.

**Comment by debop** [comment]
@johnou I know that problem ... 
so, try maven also (it need publish parent pom also) 

I will rollback to Maven ...
but, help me to publish jcenter or maven central directly in maven pom^^

**Comment by johnou** [comment]
@debop sure, just let me know when you have rolled back.

**Comment by johnou** [comment]
@debop never mind about rolling back, I am confident I can get it to work with gradle afterall.

**Comment by johnou** [comment]
@debop after further consideration and testing with gradle I think our options are..

1) roll back to Maven (allowing us to have a shaded uber jar)
2) stick with gradle but ship individual jars (with no uber jar) eg. we would have multiple artifacts hibernate-redis-hibernate4, hibernate-redis-hibernate5, hibernate-redis-hibernate52

let me know what direction you would like to go.

**Comment by debop** [comment]
I want to release merged one jar (hibernate-redis)
If use maven, build merged one jar and one sources jar, but release hibernate-redis-parent.pom also.

or separate hibernate-exampes (or exclude in maven)

I think this is best 
    1. use maven for merged jar 
    2. exclude hibernate-examples (individual maven pom.xml)

next step, add some instruction to maven pom for distribution

**Comment by johnou** [comment]
@debop sounds good. I will continue on this soon with your suggestion.

**Comment by johnou** [comment]
@debop I made a few changes to the poms and ran the release plugin mojo, here is the staging url https://oss.sonatype.org/content/repositories/comgithubdebop-1002/ let me know if this looks good or not, if yes I will proceed with release to central Maven.

**Comment by johnou** [comment]
![hibernate-redis](https://cloud.githubusercontent.com/assets/323497/19333200/0ce1a842-90f4-11e6-9ced-af44d80b7c6e.png)

**Comment by johnou** [comment]
~/.m2/settings.xml
```code
    <server>
      <id>ossrh</id>
      <username>xxx</username>
      <password>xxx</password>
    </server>
```

CLI
```code
mvn -Darguments="-Dgpg.passphrase=xxx" release:clean release:prepare release:perform -P release
```

**Comment by debop** [comment]
It seems good!
Thanks

**Comment by johnou** [comment]
Published to central Maven.
