### ISSUE TITLE
Provide the ability to read Redis-specific properties from an external source

### ISSUE THREAD

**Issue by lbornov2** [debop/hibernate-redis#40]
Currently, JedisTool relies on a private static method called "loadCacheProperties" to read redis-specific property values.  It will attempt to read from a file, which is either on the file system, or in the classpath.

This type of implementation is shortsighted, as it doesn't give the user the ability to read the values from an external data source (such as a distributed key/value system, i.e. etcd).

It would be nice to provide the ability to override this functionality.

**Comment by bostanio** [comment]
this is fixed as part of changes here: https://github.com/hibernate-redis/hibernate-redis/pull/3

Note that we are now maintaining an active fork an publishing releases from here:  https://github.com/hibernate-redis/hibernate-redis

**Comment by debop** [comment]
will support external properties with 2.x

**Comment by debop** [comment]
2.0.0 support external property file by (file:)
