### ISSUE TITLE
Serialization issue when tomcat reload

### ISSUE THREAD

**Issue by hutch13015** [debop/hibernate-redis#42]
Hello,

Thanks for your work. 

Thanks to issu https://github.com/debop/hibernate-redis/issues/19, I  can set my classloader to the conf with:
FstRedisSerializer.getConf().setClassLoader(Thread.currentThread().getContextClassLoader());

Everything works fine when my application starts. When the application reloads I have this stacktrace:

org.hibernate.PropertyAccessException: could not set a field value by reflection setter of com.myPackage.MyEnum

Caused by: java.lang.IllegalArgumentException: Can not set com.myPackage.MyEnum
 field com.MyEntity.enumAttribute to com.myPackage.MyEnum

It seems FST keeps lots of things in cache but currently we can't clear it, could you give a method to clear cached configuration

**Comment by RuedigerMoeller** [comment]
in case you need assistence/fst changes. let me know :)

**Comment by debop** [comment]
recommend using 2.0.0 with your fst
