### ISSUE TITLE
Cannot download 1.6.2 version 

### ISSUE THREAD

**Issue by z0mb1ek** [debop/hibernate-redis#43]
I see it on http://dl.bintray.com/debop/maven/com/github/debop/hibernate-redis/1.6.2/ but cannot download from maven

**Comment by johnou** [comment]
@kreyssel I have forked this project with bostanio and it has been deployed to central maven. See https://github.com/hibernate-redis/hibernate-redis

**Comment by debop** [comment]
sorry. my mistake ... missing parent pom.xml

use hibernate-redis 2.0.0
