### ISSUE TITLE
Change some log message

### ISSUE THREAD

**Issue by jeffmaury** [debop/hibernate-redis#45]
Turns out that when the Redis server is stopped, an exception message is generated every second because the expiration timer is waked up every seconds. This leads to lot of messages being generated. I think this should be changed either by changing the severity of the message or by controlling the rate at which the message is generated (for example, generate only one message per slot of 30s)

**Comment by debop** [comment]
ok.
2.x will not using custom expiration thread.

**Comment by debop** [comment]
hibernate 2.0.0 change redis client driver from Jedis to Redisson.
Redisson support expiring thread itself, so we have no custom thread for expiring.
