### ISSUE TITLE
Deploy source and javadoc to Bintray

### ISSUE THREAD

**Issue by jeffmaury** [debop/hibernate-redis#46]
Artifacts are deployed to Bintray but as of yet, only binary artifacts are deployed. To ease debugging, it should be useful to deploy also source and Javadoc artifacts

**Comment by johnou** [comment]
@jeffmaury I have forked this project with bostanio and it has been deployed to central maven with sources. See https://github.com/hibernate-redis/hibernate-redis

**Comment by jeffmaury** [comment]
Do you have an agreement with @debop ? Because if you don't ch

**Comment by johnou** [comment]
No agreement with debop as he is not responding. I don't see it being a problem, he never published to central maven and we have changed the artifact group id from io.github.debop to io.github.hibernate-redis.

**Comment by debop** [comment]
@jeffmaury , @johnou No problem. I will upload 2.x source ^^

**Comment by debop** [comment]
Hmm.... I was deploy source file (not java doc) ...
Can't access source file ?

**Comment by debop** [comment]
hibernate-redis 2.0.0 release with source
