### ISSUE TITLE
Allow configuration from hibernate configuration

### ISSUE THREAD

**Issue by jeffmaury** [debop/hibernate-redis#47]
The configuration is performed from hibernate-redis.properties configuration file. It should be great (for better integration with Spring Boot for example) if the keys could be loaded from the hibernate configuration that is given to the factory. The rationale could be that if we can't load the file (because it doesn't exist, then get the keys from the hibernate configuration.

**Comment by bostanio** [comment]
I'm pretty sure this is fixed by changes as part of this PR: https://github.com/hibernate-redis/hibernate-redis/pull/3

Note that we are now maintaining an active fork an publishing releases from here: https://github.com/hibernate-redis/hibernate-redis

**Comment by debop** [comment]
hibernate 2.0.0 support resource file and outer file.

with 'file://'  you can access outer file.
