### ISSUE TITLE
I configed redis as my hibernate's second cache, But I can't see any items in my redis.

### ISSUE THREAD

**Issue by xupanwilson** [debop/hibernate-redis#49]
1.My code to operate hibernate:
SessionFactory sessionFactory = new OracleUtils().createHibernateSessionFactory("hibernate.cfg.xml");
	sessionFactory.getStatistics().setStatisticsEnabled(true);
        sessionFactory.getStatistics().clear();
        Session session = sessionFactory.openSession();
        session.beginTransaction();
        Emp emp = new Emp((int)Math.floor(Math.random()*100 + 1));
        session.save(emp);
        session.getTransaction().commit();
        session.close();

2.My hibernate config:seems the tag "<" is not showing correctly, So I copy it as the following: 

         hibernate.connection.driver_class">oracle.jdbc.driver.OracleDriver
         hibernate.connection.password">sgbiz
         hibernate.connection.url">jdbc:oracle:thin:@10.6.0.46:1521:dlsc
         hibernate.connection.username">sgbiz
         hibernate.default_schema">SGBIZ
         hibernate.dialect">org.hibernate.dialect.Oracle10gDialect
         show_sql">true
         hibernate.cache.use_second_level_cache">true
		 hibernate.cache.use_query_cache">true
		 hibernate.cache.region.factory_class">org.hibernate.cache.redis.SingletonRedisRegionFactory
         mapping class="com.epri.dlsc.oracle.entities.Emp"

3.My hibernate-redis.properties:
 # Redis Server for hibernate 2nd cache
 redis.host=10.6.0.45
 redis.port=6379

redis.timeout=2000
redis.password=123456

 # database for hibernate cache
 # redis.database=0
 redis.database=1

 # hiberante 2nd cache default expiry (seconds)
 redis.expiryInSeconds=120

 # expiry of hibernate.common region (seconds) // hibernate is prefix, region name is common
 redis.expiryInSeconds.hibernate.common=0

 # expiry of hibernate.account region (seconds) // hibernate is prefix, region name is account
 redis.expiryInSeconds.hibernate.account=1200

4.My Emp entity:
/**

 * Emp generated by hbm2java
 */
@Entity
@Table(name = "EMP")
@Cache(region="common", usage = CacheConcurrencyStrategy.READ_WRITE)
public class Emp implements java.io.Serializable {

	private int empno;
	private String ename;
	private String job;
	private BigDecimal salary;
........

Can you give me any suggestions?

**Comment by edolphin-ydf** [comment]
try change this 
```
#redis.database=0
redis.database=1
```
to
```
redis.database=0
#redis.database=1
```

**Comment by johnou** [comment]
@xupanwilson you should really take care pasting configs like that and remove passwords.

It could be that your queries are not causing any entities to be held in second level cache, you should avoid hsql for example.

If you can also provide your DOA or better still a reproducer project we can try and help further.
