### ISSUE TITLE
2.x doesn't seem to take in the expirySeconds into account.

### ISSUE THREAD

**Issue by Chaos907** [debop/hibernate-redis#51]
I tried using the following config with the expiryInSeconds set to 7200 (2 hrs) but it's still expiring in 1 minute. I am using 2.x along with hibernate 5.1.0.FINAL.

Belong is my hibernate-redis.xml

 ##########################################################
 #
 # properities for hibernate-redis
 #
 ##########################################################

 # Redisson configuration file
 redisson-config=conf/redisson.yaml

 # Cache Expiry settings
 # 'hibernate5' is second cache prefix
 # 'common', 'account' is actual region name
 redis.expiryInSeconds.default=7200
 redis.expiryInSeconds.hibernate5.common=7200

**Comment by debop** [comment]
Oh! it was milliseconds ... I will fix it at 2.0.1

**Comment by debop** [comment]
@Chaos907 fix it 2.0.1
