### ISSUE TITLE
can not use release 1.6.2

### ISSUE THREAD

**Issue by cnticws** [debop/hibernate-redis#52]
> mvn clean package

Could not find artifact com.github.debop:hibernate-redis-parent:pom:1.6.2 in http://dl.bintray.com/debop/maven/

**Comment by debop** [comment]
@cnticws 
sorry, I missing parent pom...
upload hibernate-redis-parent pom 1.6.2 to bintray^^

check it out

**Comment by cnticws** [comment]
http://dl.bintray.com/debop/maven/com/github/debop/hibernate-redis-parent/1.6.2/

no any file yet, only an empty folder...

**Comment by debop** [comment]
sorry
because only upload not publish ... 
try it right now please.

**Comment by cnticws** [comment]
ok. thanks a lot!
