### ISSUE TITLE
Support Java 6 in FST

### ISSUE THREAD

**Issue by debop** [debop/hibernate-redis#54]
FST support Java 6 in different artifact and package name.

To support Java 6 with FST, New FST Codec needed for Redisson.
Redisson using FST which support Java 7 or higher

**Comment by johnou** [comment]
Hibernate 5.2 is built using Java 8 JDK and will require Java 8 JRE at runtime https://github.com/hibernate/hibernate-orm/wiki/Migration-Guide---5.2 , I don't think adding support for Java 6 is worth the trouble.

**Comment by debop** [comment]
We need Java 6 ㅠ.ㅠ (South Korea Government require Java 6 yet ...) 
Hibernate 5.2 big changes, we need other branch and support Java 8 or higher only.
but Hibernate 5.1.x or Lower support Java 6 or Higher
We need planning to Support Hibernate 5.1.x and Hibernate 5.2.x or Higher

**Comment by debop** [comment]
@johnou 
I commited some code to support Hibernate 5.2.x ^^

**Comment by debop** [comment]
Drop to support Java 1.6 ...
Just support 1.7 or higher
