### ISSUE TITLE
Maven repository issues

### ISSUE THREAD

**Issue by benleov** [debop/hibernate-redis#56]
Hi,

I'm trying to use Nexus to use http://dl.bintray.com/debop/maven/ to pull in 2.0.2 as a runtime dependency with gradle but its having problems.  I'm not very familiar with how maven is setup but it lists hibernate-redis-client, hibernate-redis-hibernate4 and hibernate-redis-hibernate5 as compile time dependencies however it cant find these in any repo.  Have I misconfigured Nexus or do these need to be added? Happy to help in any way I can.

**Comment by debop** [comment]
Sorry, its my mistake
Omitted merge jars.

Use 2.0.3 please

**Comment by benleov** [comment]
2.0.3 is now pulling in correctly. Thank you for your help.
