### ISSUE TITLE
Use `fastPut` methods instead of `put`

### ISSUE THREAD

**Issue by mrniko** [debop/hibernate-redis#58]
Hi!

I have reviewed your integration with Redisson. Great work! I would recommend to replace `RMapCache.put` methods to `RMapCache.fastPut` in [RedisClient](https://github.com/debop/hibernate-redis/blob/master/hibernate-redis-client/src/main/java/org/hibernate/cache/redis/client/RedisClient.java) as these methods work faster.

**Comment by johnou** [comment]
@mrniko can you explain in what cases one should use put over fastPut?

**Comment by debop** [comment]
Thanks for good sugestion.

put / fastPut is whether waiting response.
if CacheItem need not waiting response, can change to fastPut^^

I'll change to fastPut

**Comment by johnou** [comment]
Sounds like it could lead to races when inserting data into the cache?

**Comment by mrniko** [comment]
@johnou 
> Sounds like it could lead to races when inserting data into the cache?

Actually no. `put` methods always return previous value which leads to excess command execution in lua script (`hget` to get previous value) and data transfer over network.

**Comment by debop** [comment]
apply to 2.0.4-SNAPSHOT
