### ISSUE TITLE
Do we have to add @Cache annotations to @OneToMany relationships?

### ISSUE THREAD

**Issue by contentfree** [debop/hibernate-redis#60]
Started using hibernate-redis and are running into problems. We have an entity that has `CacheConcurrencyStrategy.READ_ONLY`. It also has an eager-fetched OneToMany relationship for a collection of another ready-only entity. 

When the cache is empty all the code works fine… and the cache entry is made for the entities. This is where the problem enters. As long as that entry exists in the cache, subsequent passes through the code fail – the OneToMany collection is empty!

Do we have to add the `@Cache` annotation to all the associations/relationships? Your test examples do not seem to do that, but we're experiencing this failure.

**Comment by debop** [comment]
I think @Cache for individual entity.
In Master-Detail (One-To-Many) relations, if master applied @Cache annotation, but detail entity has not applied, detail entity not cached.
All entity cached by entity identifier (classname + # + identifier) 

For more details, show me your code please.
