### ISSUE TITLE
hibernate-redis 2.0.4 with Redisson 2.3.0

### ISSUE THREAD

**Issue by debop** [debop/hibernate-redis#62]
Redisson 2.3.0 not support backward compatibility. 
if you use Redisson 2.2.x, use hibernate-redis 2.0.3 

hibernate-redis 2.0.4 using Redisson 2.3.x

**Comment by mrniko** [comment]
When do you plan to release it?

**Comment by johnou** [comment]
@debop might be worth bumping the minor version.

**Comment by debop** [comment]
@mrniko , @johnou 
I'm already release 2.0.4 ... and bumping up to 2.1.0 ^^
