### ISSUE TITLE
Is it possible to configure redisson programmatically?

### ISSUE THREAD

**Issue by GeBeater** [debop/hibernate-redis#66]
Like the Redisson documentation linked below, Redisson can be configured programmatically or declarative. For my use case, it would be more flexible to use the programmatically way. So my question is, whether it is possible to use the dedop:hibernate-redis library together with the programmatically redisson configuration?

https://github.com/mrniko/redisson/wiki/2.-Configuration

**Comment by debop** [comment]
I can't find configure in promgramatic. 
hibernate instancing RegionFactory by configuration only. ( hibernate.cache.provider_configuration_file_resource_path )

**Comment by johnou** [comment]
@debop couldn't we allow the developer to extend SingletonRedisRegionFactory and provide a callback to configure Redisson?

**Comment by debop** [comment]
Ok, that's good idea. 
I try to implement callback for programmatic configuration and others.

**Comment by johnou** [comment]
For inspiration here is how Spring boot allows customising.

```java
new EmbeddedServletContainerCustomizer() {

        @Override
        public void customize(ConfigurableEmbeddedServletContainer container) {
            if (container instanceof TomcatEmbeddedServletContainerFactory) {
                ((TomcatEmbeddedServletContainerFactory) container)
                        .addContextCustomizers(new TomcatContextCustomizer() {

                    @Override
                    public void customize(Context context) {
                        context.setCookieProcessor(new LegacyCookieProcessor());
                    }

                });
            }
        }

    };
```

**Comment by johnou** [comment]
@debop it's a good start, if you don't mind I would like to polish it a bit more.

**Comment by johnou** [comment]
There was an oversight in the implementation, fixed with https://github.com/debop/hibernate-redis/pull/74
