### ISSUE TITLE
RedisClient creates new RMapCache every time a method is invoked

### ISSUE THREAD

**Issue by johnou** [debop/hibernate-redis#75]
https://github.com/debop/hibernate-redis/blob/devel/hibernate-redis-client/src/main/java/org/hibernate/cache/redis/client/RedisClient.java#L159

```java
  private RMapCache<Object, Object> getCache(final String region) {
    return redisson.getMapCache(region);
  }
```

@debop shouldn't we be holding on to references of RMapCache? cc. @mrniko

**Comment by debop** [comment]
getMapCache method create RMapCache every called.
we need to store RegionName-RMapCache in RedisClient.

**Comment by mrniko** [comment]
RMapCache object creation is cheap operation in terms of memory and cpu resource, but you can cache these instances if you want

**Comment by johnou** [comment]
@debop maybe ConcurrentHashMap computeIfAbsent or something? We should run a benchmark to see if it's worth the extra boiler-plate code.

**Comment by johnou** [comment]
@mrniko thanks, I wondered if some weirdness could manifest as a result of the multiple instances.

**Comment by johnou** [comment]
@debop something like this? Could also cache / lazy init RScript (used in nextTimestamp).

```java
  private final ConcurrentMap<String, RMapCache<Object, Object>> caches = new ConcurrentHashMap<String, RMapCache<Object, Object>>();

  private RMapCache<Object, Object> getCache(final String region) {
    RMapCache<Object, Object> cache = caches.get(region);
    if (cache == null) {
      cache = redisson.getMapCache(region);
      RMapCache<Object, Object> concurrent = caches.putIfAbsent(region, cache);
      if (concurrent != null) {
        cache = concurrent;
      }
    }
    return cache;
  }
```

**Comment by debop** [comment]
@johnou , exactly.
