### ISSUE TITLE
Does this support READ_WRITE strategy

### ISSUE THREAD

**Issue by shougaoshougao** [debop/hibernate-redis#86]
Q1.Does this support READ_WRITE strategy ? If yes, how is this implemened ? Since redis does not have lock. Can you provide a more detailed document telling features that this library supports ?

Q2.How to set cache live time and idle time for default config and each entity class?

**Comment by mrniko** [comment]
> Since redis does not have lock

@debop @johnou You could use RLock object

**Comment by mrniko** [comment]
@shougaoshougao 

Use `redis.expiryInSeconds......` settings shown in example https://github.com/debop/hibernate-redis#redis-settings-for-hibernate-redis

**Comment by debop** [comment]
@mrniko Thanks your information.
@shougaoshougao we does not support lock yet. In READ_WRITE strategy, we does not lock, just remove cache in current
