### ISSUE TITLE
Add hibernate-redis to Maven Central

### ISSUE THREAD

**Issue by skyebook** [debop/hibernate-redis#9]
First, thanks for the work you've put into this great project!

If I understand the README correctly, it seems that you aren't sure how to add this project to the Maven Central repository.  I would like to help get this into the central repository if that is possible.

**If this is not a task you're interested in undertaking, I would be happy to make some of the minor changes needed and create pull requests, or do the full process myself.**
### groupId

The group ID must be unique to the project and controlled by the maintainer.  In the case of this project, `com.github.debop` would make the most sense.
### artifactId

The artifactId, `hibernate-redis` will work as it currently is.
### version

`1.5.5` seems like the current version.
## Package Signing

The important bits here are that you must sign your artifacts and the key must be available through a public PGP key server.  Relevant information on how to do this is located here: https://docs.sonatype.org/display/Repository/How+To+Generate+PGP+Signatures+With+Maven
## Distribution to Repository

The easiest way to get this up would likely be to use the Sonatype OSS repository doing a manual upload.  Since this seems to be a fairly low-frequency project, that should be an OK way to get started. (See https://docs.sonatype.org/display/Repository/Uploading+3rd-party+Artifacts+to+The+Central+Repository)

**Comment by contentfree** [comment]
Can central be updated with 2.x?
